### PR TITLE
Fix total mAP computation.

### PR DESCRIPTION
**Pull request by vcarpani**

### CODE REVIEW

**Comment by enricoliscio** [comment]
LGTM. Add a little comment that it's the weighted sum over the total instances and not the classes, then you can merge.

**Comment by hgaiser** [comment]
Maybe this should be an option and not the default? I agree this makes much more sense, but traditionally (COCO) it is not computed as a weighted sum.

**Comment by vcarpani** [comment]
Sure, will fix it tomorrow, should we leave the COCO style as default?

**Comment by hgaiser** [comment]
Yeah I think that makes sense.

**Comment by enricoliscio** [comment]
LGTM. You can merge.

**Pull request merged**
