### PR TITLE
Modify wudi

### PR DESCRIPTION
**Pull request by fangwudi**
delete unused line

### CODE REVIEW

**Comment by hgaiser** [comment]
Thanks! What is the deal with the updated .gitignore though?

**Comment by fangwudi** [comment]
@hgaiser  github reminds me there's a conflict in .gitigore. but i failed to solve it.

**Comment by hgaiser** [comment]
Hmm okay, if you can resolve that issue I'll merge this PR :)

**Comment by de-vri-es** [comment]
We can keep `*.pyc` in `.gitignore` as far as I'm concerned. However, the rest doesn't seem suitable for the versioned `.gitignore`.

**Comment by hgaiser** [comment]
`*.pyc` is actually already in the [`.gitignore`](https://github.com/fizyr/keras-retinanet/blob/master/.gitignore).

**Comment by de-vri-es** [comment]
Oh, then it should go :)

**Comment by fangwudi** [comment]
done @hgaiser  thanks guys @de-vri-es

**Comment by hgaiser** [comment]
Merged, thanks!

**Pull request merged**
