### PR TITLE
Update tensorboard writer for tf version >= 2.0.0

### PR DESCRIPTION
**Pull request by sedthh**
- updated writer for eval.py
- updated writer for coco.py

`log_dir` is accessed via `self.tensorboard.log_dir` which can be assigned via `--tensorboard-dir` 

However, the rest of the arguments (such as `--tensorboard-freq`) are ignored.

### CODE REVIEW

**Comment by hgaiser** [comment]
Since we don't support tensorflow < 2.3, could you update the PR to use tensorflow 2?

**Comment by sedthh** [comment]
Just to make it clear, do you want me to remove the legacy code for tf < 2.0.0. and only have the new one included?
Should I check for versions or raise an Exception if the version is lower?

**Comment by hgaiser** [comment]
Yeah exactly. We are already checking for tensorflow version: https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/bin/train.py#L471-L472

Oh btw I forgot to mention it earlier, but thanks for your PR :)

**Comment by sedthh** [comment]
I have imported `check_tf_version()` also because the evaluation could be called outside of main. Is this ok or should I not include it?

**Comment by sedthh** [comment]
Realized `check_tf_version()` is already called at evaluate.py so it does not need to be called again in the callbacks.

**Comment by hgaiser** [comment]
Yep :) thanks again, looks good to me :+1:

**Pull request merged**
