### PR TITLE
Assert outputs before converting to inference model.

### PR DESCRIPTION
**Pull request by hgaiser**
There have been quite some issues because people try to convert an already converted model. This PR adds a check that the outputs at least contain a `regression` and `classification` output (which isn't the case in a converted model).

### CODE REVIEW

**Comment by de-vri-es** [comment]
Good idea. Only the current implementation will result in a stack trace though if the assertion fails.

How about splitting this into a separate utility function to check if the model has the required outputs, so that at least `convert_model.py` can check it and print a clean error message without stack trace? That would be similar to the way the minimum keras version is checked in the scripts.

**Comment by hgaiser** [comment]
I updated the PR, what do you think @de-vri-es ?

**Comment by de-vri-es** [comment]
The extra function looks good, but I don't think the function `default_classification_model` should call `sys.exit` (indirectly). That's really something I would only do from the scripts themselves, but not from other library functions (apart from `check_training_model` itself).

**Comment by enricoliscio** [comment]
Looks good, good idea.

**Pull request merged**
