### PR TITLE
Encode regression as x1/y1/x2/y2.

### PR DESCRIPTION
**Pull request by hgaiser**
This PR changes the way the regression is encoded. It used to be x_ctr/y_ctr/w/h, but this PR changes that to x1/y1/x2/y2 which seems to have a small positive effect on the mAP:

Before:
```
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.345
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.533
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.368
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.189
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.380
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.465
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.301
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.482
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.529
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.364
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.565
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.666
```

After:
```
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.350                                                               
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.536                                                               
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.373                                                               
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.188                                                               
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.384                                                               
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.470                                                               
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.307                                                               
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.491                                                               
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.533                                                               
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.343                                                               
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.577                                                               
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.678
```

### CODE REVIEW

**Comment by de-vri-es** [comment]
This now also includes the nearest neighbour upscaling. Anyway, assuming it's tested, looks good.

Will this be incompatible with older weights though?

**Comment by hgaiser** [comment]
Yeah this will make previous weights incompatible.

**Comment by hgaiser** [comment]
I'm thinking we should call this v0.3, what do you think @de-vri-es ?

**Comment by de-vri-es** [comment]
Makes sense I think.

**Pull request merged**
