### PR TITLE
Implemented F1 score for assessments.

### PR DESCRIPTION
**Pull request by SalahAdDin**
I'm working on that but it seems i don't understand how to get that value, so, if you can help me, it would be great, thanks.

### CODE REVIEW

**Comment by hgaiser** [comment]
Thanks for the PR! I'm not sure about the use case for computing the F1 score though. All object detection datasets I know use some form of mAP to report there accuracy. Why do you think the F1 score should be added?

**Comment by SalahAdDin** [comment]
Because, if you review most of academic articles, they no only use mAP, they also use F1 score to compare the performance along the different deep learning techniques.

I could add here all articles that use it, also my thesis advisor requires from me F1 score; it is, as far as i know, a standar in the computer sciences.

This implementation is not perfect and it is nor working: F1 score should be between 0.0 to 1.0, but i'm getting values over 1.0.

Thanks.

**Comment by SalahAdDin** [comment]
All help is welcome.

**Comment by SalahAdDin** [comment]
@hgaiser Did you implement _F1 score_ in your _py-faster-rcnn_  implementation?

**Comment by hgaiser** [comment]
Could you also update the code [here](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/callbacks/eval.py#L63) ?

> @hgaiser Did you implement _F1 score_ in your _py-faster-rcnn_ implementation?

What py-faster-rcnn implementation do  you mean?

**Comment by SalahAdDin** [comment]
Done.

I got it wrong, it was commented here: https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/utils/eval.py#L33

**Comment by hgaiser** [comment]
Thank you for the PR :)

**Comment by SalahAdDin** [comment]
@MiguelAngelL07 You can add it making a PR. Please.
@hgaiser Did you review this? it was not working for me,

**Comment by SalahAdDin** [comment]
I found the definition of [**F1**:](https://arxiv.org/pdf/1807.11809.pdf)  

> The harmonic mean of precision and recall. For multi-class
> classification problems, F1 gets averaged among all the classes. It is
> mentioned as F-measure in (Minh, et al., 2017).
> F1=2 * (TP*FP) / (TP+FP)

So, I implemented this wrong.

**Comment by hgaiser** [comment]
@SalahAdDin can you make a PR to correct it?

**Comment by SalahAdDin** [comment]
@hgaiser I don't have time to do it now, i'll appreciate your help here.

**Comment by hgaiser** [comment]
> @hgaiser I don't have time to do it now, i'll appreciate your help here.

Unfortunately I am also quite limited in my time.

**Pull request merged**
