### PR TITLE
Optional choose specific GPU to convert model

### PR DESCRIPTION
**Pull request by void32**
Option to select which GPU to use when converting a model as in _evaluate.py_.

### CODE REVIEW

**Comment by hgaiser** [comment]
Thanks for the PR! Actually I've thought about this before but never changed it, but could you change it to use the CPU instead of the GPU? There's no benefit to use a GPU here really.. Wrapping `models.load_model` with [this](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/bin/train.py#L107) should be sufficient (but please test it to make sure it is actually using the CPU :)).

**Comment by void32** [comment]
Hi hgaiser,
Yes of course, I was also a bit surprised when i used the GPU:-) 
However, I tried wrapping with tf.device('/cpu:0') but it didn't work. Instead I had to set _CUDA_VISIBLE_DEVICES_ to empty.

**Comment by hgaiser** [comment]
Alright, that'll work for me :)

Could you resolve the flake8 error? After that I'll merge it.

**Comment by hgaiser** [comment]
Perfect, thanks!

**Pull request merged**
