### PR TITLE
Pyramid level customization

### PR DESCRIPTION
**Pull request by mooratov**
made pyramid levels configurable, and implemented the capability to use P2 pyramid layer. 
Currently, P2 layers only works for Resnet backbone.

### CODE REVIEW

**Comment by mooratov** [comment]
very sorry, this was supposed to go on my personal fork (not ready for primetime)

**Comment by muaali** [comment]
@mooratov I am trying to understand what is the benefit of using P2 and C2 in retinanet. 
Also did it benefit you in some way, in terms of performance. What was the scale / size of objects that you were trying to detect. Thanks.

**Comment by mooratov** [comment]
we were interested in very small bounding boxes, on the scale of 4x4 pixels
or so.

**Comment by muaali** [comment]
Thanks @mooratov . I will use your commits to include C2-P2 in the model and then to train the model and see if it learns better.

**Pull request closed without merging**
