### PR TITLE
Avoid importing numpy in setup.py

### PR DESCRIPTION
**Pull request by maxclaey**
With the current setup.py file, keras-retinanet cannot be installed if numpy is not present.
With the updated version, numpy is specified as a dependency of keras-retinanet and is installed on the fly if needed.

### CODE REVIEW

**Comment by de-vri-es** [comment]
+1 for not required numpy in `setup.py`. However, why do we need it in the first place? Can't we just declare numpy as a dependency and be done with it?

**Comment by maxclaey** [comment]
I assume that to build the compute_overlap extension, Cython has to know where to find the numpy header files, hence the np.get_include(). I tried to solve this by adding numpy as a setup dependency, and only importing numpy at runtime. However, this would just move the problem to requiring Cython. Therefore, the custom_wrapper closure was needed. Now all works fine when installing with pip, but unfortunately, building with setup.py fails (causing the failed Travis CI build). At the moment I don't see an easy way to solve this without importing Cython earlier, and thus causing the same problem as we initially had with numpy.

**Comment by de-vri-es** [comment]
hmm, I see.. I would really like if we can install properly with pip and `setup.py`. Any idea why running `setup.py` directly doesn't work anymore?

**Comment by maxclaey** [comment]
The error that pops up is the following:
`distutils.errors.DistutilsClassError: command class <class '__main__.custom_wrapper'> must subclass Command`
The problem is that custom_wrapper should extend the Cython build_ext, but we can't do that immediately, as that would require us to import Cython. That's why the closure is used, and constructing custom_wrapper returns a custom_build_ext that dóes extend build_ext. But apparently some checks are done on custom_wrapper itself. I'm by far no expert on this, so I don't really know how to circumvent this.

**Comment by de-vri-es** [comment]
I pushed a commit which I think should fix the issue.

I'm not sure why you had to create an additional wrapper class, but this seems to work as intended. To test, I removed both cython and numpy from my system, then ran `pip install --user .`.  It downloaded all the required dependencies (including numpy and cython) without causing any import errors.

Running `python setup.py build_ext --inplace` directly also worked.

@maxclaey: Could you review the commit I pushed?

**Comment by maxclaey** [comment]
I just tested it again in a new fresh environment, just to be sure that I didn't overlook anything yesterday, but I get the same problem again. This is part of the output of `pip install .`
```running build_ext
  building 'keras_retinanet.utils.compute_overlap' extension
  error: unknown file type '.pyx' (from 'keras_retinanet/utils/compute_overlap.pyx')
  
  ----------------------------------------
  Failed building wheel for keras-retinanet```
This is because because when you import build_ext from setuptools.command.build_ext, it checks if Cython is present. It needs Cython to be able to handle .pyx files. That's why I needed the extra wrapper to be sure to only load build_ext when Cython is already installed. It's an option to provide a precompiled compute_overlap.c file as a fallback for when Cython is not present, but I'm not sure that's the way to go..

**Comment by de-vri-es** [comment]
I don't understand why I don't get that error. I can run `pip install --user .` fine without cython installed. Which version of python and pip are you using exactly?

I'm on python 3.7.1 and pip 18.0

**Comment by de-vri-es** [comment]
Hmm, weird. However, I pushed another attempt that still works for me with both pip and `setup.py` invoked directly.

**Comment by maxclaey** [comment]
Just tested your new approach, works like a charm this time. Also tests are passing. Great work @de-vri-es , thanks a lot!

**Comment by de-vri-es** [comment]
Good to hear, thanks for the PR, and thanks for testing. Merging :)

**Pull request merged**
