### PR TITLE
Implement BackboneMeta class.

### PR DESCRIPTION
**Pull request by hgaiser**
This PR implements the `BackboneMeta` class, which holds meta information of backbones. This information can be used for backbone specific functions, such as imagenet weights downloading, custom objects, etc.

### CODE REVIEW

**Comment by de-vri-es** [comment]
In general I think this is the right approach. I'm not very enthusiastic about the name `BackboneMeta` though. What about simply `Backbone` or if it has to be more complicated `BackboneDescription` or even `BackbonePlugin`?

**Comment by hgaiser** [comment]
Would we then get a `ResNetBackbone` if we rename it to `Backbone`?

**Comment by de-vri-es** [comment]
I think so.

**Comment by hgaiser** [comment]
Updated, awaiting CI.

**Comment by hgaiser** [comment]
Damn, nice catch :)

https://github.com/fizyr/keras-retinanet/commit/e4d8b9679b4b895b24b8eb889d6157bd50f1f523

**Comment by de-vri-es** [comment]
cheer :beers:

**Pull request merged**
